"""Read/write snapshot .py + .bat files and configs.yaml.

The launcher's CRUD edits a small set of *editable constants* in each
snapshot's start_*.py file. Everything else (env overlay, args list,
manifest write) is structural and should not be touched from the UI ,
those concerns live in _common.py and the snapshot template.

Editable constants (single-source-of-truth list):

    PORT                    int
    TP                      int
    PP                      int
    USE_MTP                 bool
    NUM_SPEC_TOKENS         int
    CTX                     int
    GPU_MEM_UTIL            float
    MAX_NUM_BATCHED_TOKENS  int

Save flow on edit:
    - rewrite the corresponding `<NAME> = ...` line in the .py file
    - rewrite the matching `${SNAPSHOTS_DIR}\\<bat>` entry in configs.yaml

Save flow on new/duplicate:
    - copy a source .py to <new>.py
    - replace constants
    - emit a thin <new>.bat from the start_speed.bat template
    - append entry to configs.yaml
"""
from __future__ import annotations

import os
import re
import shutil
from pathlib import Path
from typing import Any

import yaml

from .config import CONFIGS_PATH, WinConfig, _resolve_env


_BAT_TEMPLATE = """\
@echo off
REM {basename}.bat -- generated by launcher
setlocal
cd /d "%~dp0"
set "REPO_ROOT=%~dp0.."
set "PY="
if defined VLLM_WINDOWS_VENV if exist "%VLLM_WINDOWS_VENV%\\Scripts\\python.exe" set "PY=%VLLM_WINDOWS_VENV%\\Scripts\\python.exe"
if not defined PY if exist "%REPO_ROOT%\\venv\\Scripts\\python.exe" set "PY=%REPO_ROOT%\\venv\\Scripts\\python.exe"
if not defined PY if exist "%REPO_ROOT%\\python\\python.exe" set "PY=%REPO_ROOT%\\python\\python.exe"
if not defined PY (
    echo [{basename}.bat] no python interpreter found under %REPO_ROOT%
    pause
    exit /b 1
)
"%PY%" -u "%~dp0{basename}.py" %*
set "RC=%ERRORLEVEL%"
if not "%RC%"=="0" (
    echo.
    echo [{basename}.bat] exited with code %RC%
    pause
)
endlocal & exit /b %RC%
"""


# Each entry: (constant name, regex matching the assignment line, formatter for new value)
def _fmt_int(v: Any) -> str:
    return str(int(v))

def _fmt_float(v: Any) -> str:
    f = float(v)
    s = f"{f:.4f}".rstrip("0").rstrip(".")
    return s if s else "0"

def _fmt_bool(v: Any) -> str:
    return "True" if bool(v) else "False"


# (name, py_type) for the eight editable constants. Order = display order in form.
EDITABLE_CONSTS: list[tuple[str, str]] = [
    ("PORT", "int"),
    ("TP", "int"),
    ("PP", "int"),
    ("USE_MTP", "bool"),
    ("NUM_SPEC_TOKENS", "int"),
    ("CTX", "int"),
    ("GPU_MEM_UTIL", "float"),
    ("MAX_NUM_BATCHED_TOKENS", "int"),
]


def _const_regex(name: str) -> re.Pattern:
    # Match `NAME = <value>` with optional inline comment, at line start.
    return re.compile(rf"^(?P<lead>{name}\s*=\s*)(?P<val>[^#\n]+?)(?P<tail>\s*(?:#.*)?)$", re.MULTILINE)


_REGEX_CACHE = {name: _const_regex(name) for name, _ in EDITABLE_CONSTS}


def update_py_constants(py_path: Path, values: dict[str, Any]) -> list[str]:
    """Rewrite editable constants in `py_path` in place.

    Returns a list of human-readable change descriptions for status display.
    Constants not present in the file are appended after the imports block ,
    this lets a simple .py without USE_MTP still gain it on first edit.
    """
    src = py_path.read_text(encoding="utf-8")
    changes: list[str] = []

    for name, kind in EDITABLE_CONSTS:
        if name not in values or values[name] is None:
            continue
        new_val = values[name]
        if kind == "int":
            new_repr = _fmt_int(new_val)
        elif kind == "float":
            new_repr = _fmt_float(new_val)
        else:
            new_repr = _fmt_bool(new_val)

        rx = _REGEX_CACHE[name]
        m = rx.search(src)
        if m:
            old_repr = m.group("val").strip()
            if old_repr == new_repr:
                continue
            src = src[:m.start("val")] + new_repr + src[m.end("val"):]
            changes.append(f"{name}: {old_repr} -> {new_repr}")
        else:
            # Constant doesn't exist in this file. Skip silently rather than
            # injecting random globals, most snapshots that lack USE_MTP
            # don't want it. The form value is ignored for missing fields.
            continue

    py_path.write_text(src, encoding="utf-8")
    return changes


def read_py_constants(py_path: Path) -> dict[str, Any]:
    """Parse current values of editable constants from a .py file.

    Used by the form's Revert button + initial load. Missing constants
    return None, the form treats None as 'not applicable'.
    """
    out: dict[str, Any] = {}
    if not py_path.exists():
        return out
    src = py_path.read_text(encoding="utf-8")
    for name, kind in EDITABLE_CONSTS:
        m = _REGEX_CACHE[name].search(src)
        if not m:
            out[name] = None
            continue
        raw_val = m.group("val").strip()
        try:
            if kind == "int":
                out[name] = int(raw_val)
            elif kind == "float":
                out[name] = float(raw_val)
            else:
                out[name] = raw_val.lower() == "true"
        except ValueError:
            out[name] = None
    return out


def copy_py_template(source_py: Path, dest_py: Path, values: dict[str, Any]) -> list[str]:
    """Copy source_py to dest_py, then update_py_constants.

    `dest_py` must not already exist (caller checks).
    """
    if dest_py.exists():
        raise FileExistsError(str(dest_py))
    shutil.copy2(source_py, dest_py)
    return update_py_constants(dest_py, values)


def write_bat(bat_path: Path) -> None:
    """Emit a thin bat that runs <basename>.py via the resolved python."""
    basename = bat_path.stem
    bat_path.write_text(_BAT_TEMPLATE.format(basename=basename), encoding="utf-8")


def delete_snapshot_files(py_path: Path, bat_path: Path) -> list[str]:
    """Best-effort delete of the .py and .bat. Returns list of removed paths."""
    removed: list[str] = []
    for p in (py_path, bat_path):
        try:
            p.unlink()
            removed.append(str(p))
        except FileNotFoundError:
            pass
        except OSError:
            pass
    return removed


# ---- configs.yaml round-trip ------------------------------------------------

# Ordered key list controls how each config block is written. Keys not in
# this list are appended after, sorted alphabetically. Comment-free output
# (PyYAML can't preserve comments anyway) but the ordering stays human-friendly.
_CONFIG_KEY_ORDER = [
    "id", "tagline", "tier", "status",
    "bat", "py",
    "gpu", "tp", "pp", "mem_util",
    "mtp_n", "draft_model_n",
    "ctx", "port",
    "decode_tps", "decode_tps_short", "decode_tps_long",
    "prefill_tps_cold",
    "power_cap_w",
    "notes",
]


def _ordered_config(c: dict) -> dict:
    out: dict = {}
    for k in _CONFIG_KEY_ORDER:
        if k in c:
            out[k] = c[k]
    for k in sorted(c.keys()):
        if k not in out:
            out[k] = c[k]
    return out


def _unsubstitute_paths(s: str, env: dict[str, str]) -> str:
    """Reverse of _expand_placeholders for one string, turn absolute path
    fragments back into ${SNAPSHOTS_DIR}\\... so the file reads cleanly."""
    if not isinstance(s, str):
        return s
    for k, v in env.items():
        if not v:
            continue
        # case-insensitive replace on Windows path values
        if v.lower() in s.lower():
            idx = s.lower().find(v.lower())
            s = s[:idx] + "${" + k + "}" + s[idx + len(v):]
    return s


def _unsubstitute_recursive(obj: Any, env: dict[str, str]) -> Any:
    if isinstance(obj, str):
        return _unsubstitute_paths(obj, env)
    if isinstance(obj, dict):
        return {k: _unsubstitute_recursive(v, env) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_unsubstitute_recursive(v, env) for v in obj]
    return obj


def save_configs_yaml(bundle, configs_path: Path | None = None) -> Path:
    """Re-emit configs.yaml from `bundle` with placeholders re-substituted.

    bundle.windows[*].raw holds the per-config dict that was loaded from disk
    (post-substitution). We update the editable scalar fields from the
    WinConfig dataclass back into raw, then dump.
    """
    target = configs_path or CONFIGS_PATH
    env = _resolve_env()

    # Sync dataclass fields back into the raw dicts so the dump has the
    # latest values from the form.
    serialised: list[dict] = []
    for c in bundle.windows:
        raw = dict(c.raw) if c.raw else {}
        raw["id"] = c.id
        raw["tagline"] = c.tagline
        raw["tier"] = c.tier
        raw["status"] = c.status
        raw["bat"] = c.bat
        raw["py"] = c.py
        raw["gpu"] = c.gpu
        raw["tp"] = int(c.tp)
        raw["pp"] = int(c.pp)
        raw["mem_util"] = float(c.mem_util)
        raw["ctx"] = int(c.ctx)
        raw["port"] = int(c.port)
        if c.mtp_n is None: raw.pop("mtp_n", None)
        else: raw["mtp_n"] = int(c.mtp_n)
        if c.draft_model_n is None: raw.pop("draft_model_n", None)
        else: raw["draft_model_n"] = int(c.draft_model_n)
        for fld in ("decode_tps", "decode_tps_short", "decode_tps_long",
                    "prefill_tps_cold", "power_cap_w"):
            v = getattr(c, fld)
            if v is None: raw.pop(fld, None)
            else: raw[fld] = v
        raw["notes"] = c.notes or ""
        serialised.append(_ordered_config(raw))

    # Reverse the placeholder substitution on path fields so the file
    # round-trips cleanly across machines.
    serialised = _unsubstitute_recursive(serialised, env)

    # Top-level structure preservation: re-load the existing file's structure
    # then replace just the `windows.configs` list. Keeps shared_defaults,
    # mtp_sweep, compatibility_matrix, linux section, and any future top-level
    # keys we don't know about intact.
    raw_disk = yaml.safe_load(target.read_text(encoding="utf-8"))
    raw_disk["windows"]["configs"] = serialised

    # Use literal block scalar (|) for multi-line strings (notes), so the
    # round-tripped file looks like the human-edited one and the diff stays
    # localised to actually-changed fields.
    class _Dumper(yaml.SafeDumper):
        # Indent list items so they sit two spaces past their parent key,
        # matching the project's hand-written style (`  configs:\n    - id: ...`).
        def increase_indent(self, flow=False, indentless=False):
            return super().increase_indent(flow, False)

    def _str_representer(dumper, data):
        if isinstance(data, str) and "\n" in data:
            return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
        return dumper.represent_scalar("tag:yaml.org,2002:str", data)
    _Dumper.add_representer(str, _str_representer)

    out = yaml.dump(
        raw_disk,
        Dumper=_Dumper,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
        width=120,
    )
    # Atomic write
    tmp = target.with_suffix(target.suffix + ".tmp")
    tmp.write_text(out, encoding="utf-8")
    os.replace(tmp, target)
    return target


# ---- WinConfig <-> form dict translation ------------------------------------

def cfg_to_form(c: WinConfig) -> dict[str, Any]:
    return {
        "id": c.id,
        "tagline": c.tagline,
        "tier": c.tier,
        "status": c.status,
        "bat": c.bat,
        "py": c.py,
        "gpu": c.gpu,
        "tp": c.tp,
        "pp": c.pp,
        "mem_util": c.mem_util,
        "mtp_n": c.mtp_n,
        "ctx": c.ctx,
        "port": c.port,
        "decode_tps": c.decode_tps,
        "prefill_tps_cold": c.prefill_tps_cold,
        "power_cap_w": c.power_cap_w,
        "notes": c.notes,
    }


def form_to_cfg(form: dict[str, Any], existing_raw: dict | None = None) -> WinConfig:
    raw = dict(existing_raw) if existing_raw else {}
    return WinConfig(
        id=str(form["id"]).strip(),
        tagline=str(form.get("tagline", "")).strip(),
        tier=str(form.get("tier", "active")).strip() or "active",
        status=str(form.get("status", "experimental")).strip() or "experimental",
        bat=str(form.get("bat", "")).strip(),
        py=str(form.get("py", "")).strip(),
        gpu=str(form.get("gpu", "GPU1")).strip() or "GPU1",
        tp=int(form.get("tp") or 1),
        pp=int(form.get("pp") or 1),
        mem_util=float(form.get("mem_util") or 0.92),
        ctx=int(form.get("ctx") or 32000),
        port=int(form.get("port") or 5001),
        mtp_n=int(form["mtp_n"]) if form.get("mtp_n") not in (None, "") else None,
        draft_model_n=int(form["draft_model_n"]) if form.get("draft_model_n") not in (None, "") else None,
        decode_tps=float(form["decode_tps"]) if form.get("decode_tps") not in (None, "") else None,
        prefill_tps_cold=float(form["prefill_tps_cold"]) if form.get("prefill_tps_cold") not in (None, "") else None,
        power_cap_w=int(form["power_cap_w"]) if form.get("power_cap_w") not in (None, "") else None,
        notes=str(form.get("notes", "")),
        raw=raw,
    )
